/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\BearDecor.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BearDecor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bear_decoration.geometry} material={materials['default']} />
      <mesh geometry={nodes.Bear_decoration_1.geometry} material={materials.Bear1} />
    </group>
  )
}

useGLTF.preload('/BearDecor.glb')
