/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\StorageCabinetUpdated.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/StorageCabinetUpdated.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.left_plank.geometry} material={materials.Material} position={[0.002, 0.003, -0.006]} />
      <mesh geometry={nodes.right_plank.geometry} material={materials['Material.003']} position={[0.004, 0.148, -1.484]} />
      <mesh geometry={nodes.top_plank.geometry} material={materials['Material.002']} position={[-0.001, 1.023, -0.744]} />
      <mesh geometry={nodes.bottom_plank.geometry} material={materials['Material.004']} position={[-0.008, -1.025, -0.742]} />
      <mesh geometry={nodes.back_plank.geometry} material={materials['Material.005']} position={[-0.6, 0.001, -0.746]} scale={[1, 0.958, 0.946]} />
      <mesh geometry={nodes.door.geometry} material={materials['Material.001']} position={[0.624, 0.033, -1.446]} scale={[1.166, 1, 1]} />
      <mesh geometry={nodes.hinge_top.geometry} material={materials['Material.006']} position={[0.522, 0.743, -1.449]} />
      <mesh geometry={nodes.hinge_bottom.geometry} material={materials['Material.006']} position={[0.522, -0.64, -1.449]} />
      <mesh geometry={nodes.inner_shelf.geometry} material={materials.Material} position={[-0.039, -0.202, -0.744]} scale={[0.893, 0.71, 0.922]} />
      <mesh geometry={nodes.edges.geometry} material={materials['Material.012']} position={[0.647, -0.046, -1.484]} rotation={[0, 0, -Math.PI]} scale={[-0.018, -1, -0.027]} />
    </group>
  )
}

useGLTF.preload('/StorageCabinetUpdated.glb')
