/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\BatCreature.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import BatCreatureGlb from "../modals/BatCreature.glb";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(BatCreatureGlb);
  const { actions } = useAnimations(animations, group);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={[0.8, 0.6, 0.8]}
      position={[0.5, -0.2, -0.7]}
      // rotation={[0, Math.PI / 2, 0]}
    >
      <group name="Scene">
        <group name="batCat_Rigging">
          <primitive object={nodes.roothip} />
          <primitive object={nodes.wtl1L} />
          <primitive object={nodes.wtl2L} />
          <primitive object={nodes.wtl3L} />
          <primitive object={nodes.wtl1R} />
          <primitive object={nodes.wtl2R} />
          <primitive object={nodes.wtl3R} />
          <skinnedMesh
            name="batCat_fangs"
            geometry={nodes.batCat_fangs.geometry}
            material={materials.batCat_fangs}
            skeleton={nodes.batCat_fangs.skeleton}
          />
          <skinnedMesh
            name="batCat_lowPoly"
            geometry={nodes.batCat_lowPoly.geometry}
            material={materials.batCat_Material}
            skeleton={nodes.batCat_lowPoly.skeleton}
          />
          <skinnedMesh
            name="eyeHolderLeft"
            geometry={nodes.eyeHolderLeft.geometry}
            material={materials.batCatEye_Matt1}
            skeleton={nodes.eyeHolderLeft.skeleton}
          />
          <skinnedMesh
            name="eyeHolderRight"
            geometry={nodes.eyeHolderRight.geometry}
            material={materials.batCatEye_Matt1}
            skeleton={nodes.eyeHolderRight.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(BatCreatureGlb);
