/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\BearDecor.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import BearDecorGlb from "../modals/BearDecor.glb";

/**
 * Model component renders a 3D model imported from a GLB file.
 * It utilizes GLTFLoader to load the model's nodes and materials.
 * @param {Object} props - Props for positioning and scaling the model.
 * @returns {JSX.Element} - React component representing the 3D model.
 */
export default function Model(props) {
  // Load the GLTF model and extract nodes and materials
  const { nodes, materials } = useGLTF(BearDecorGlb);

  // Render the 3D model and its components
  return (
    <group {...props} dispose={null} scale={[0.1, 0.1, 0.1]}>
      <mesh
        geometry={nodes.Bear_decoration.geometry}
        material={materials["default"]}
      />
      <mesh
        geometry={nodes.Bear_decoration_1.geometry}
        material={materials.Bear1}
      />
    </group>
  );
}

// Preload the GLTF model to ensure it's ready for rendering when used in the application
useGLTF.preload(BearDecorGlb);
