/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\BearDecor.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import BearDecorGlb from "../modals/BearDecor.glb";

export default function Model(props) {
  const { nodes, materials } = useGLTF(BearDecorGlb);

  return (
    <group {...props} dispose={null} scale={[0.1, 0.1, 0.1]}>
      <mesh
        geometry={nodes.Bear_decoration.geometry}
        material={materials["default"]}
      />
      <mesh
        geometry={nodes.Bear_decoration_1.geometry}
        material={materials.Bear1}
      />
    </group>
  );
}

useGLTF.preload(BearDecorGlb);
