/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\Book.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import BookGlb from "../modals/Book.glb";

export default function Model(props) {
  const { nodes, materials } = useGLTF(BookGlb);
  return (
    <group
      {...props}
      dispose={null}
      scale={[3, 3, 3]}
      position={[0.2, -0.1, -0.8]}
    >
      <mesh
        geometry={nodes.greenbook.geometry}
        material={materials.greenbook}
      />
      <mesh
        geometry={nodes.brownbook.geometry}
        material={materials.brownbook}
        position={[0.002, 0.049, 0]}
        rotation={[0, 0.283, 0]}
      />
    </group>
  );
}

useGLTF.preload(BookGlb);
