/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\Book.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import BookGlb from "../modals/Book.glb";

/**
 * Model component renders a 3D model imported from a GLB file.
 * It utilizes GLTFLoader to load the model's nodes and materials.
 * @param {Object} props - Props for positioning and scaling the model.
 * @returns {JSX.Element} - React component representing the 3D model.
 */
export default function Model(props) {
  // Load the GLTF model and extract nodes and materials
  const { nodes, materials } = useGLTF(BookGlb);

  // Render the 3D model and its components
  return (
    <group
      {...props}
      dispose={null} // Prevent auto-disposal of this group
      scale={[3, 3, 3]} // Scale the model for appropriate size in the scene
      position={[0.2, -0.1, -0.8]} // Position the model in 3D space
    >
      <mesh
        geometry={nodes.greenbook.geometry}
        material={materials.greenbook}
      />
      <mesh
        geometry={nodes.brownbook.geometry}
        material={materials.brownbook}
        position={[0.002, 0.049, 0]} // Adjusted position for the brown book
        rotation={[0, 0.283, 0]} // Adjusted rotation for the brown book
      />
    </group>
  );
}

// Preload the GLTF model to ensure it's ready for rendering when used in the application
useGLTF.preload(BookGlb);
