/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\CandleStickGlb.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import CandleStickGlb from "../modals/CandleStickGlb.glb";

/**
 * Model component renders a 3D candlestick imported from a GLB file.
 * It utilizes GLTFLoader to load the model's nodes and materials.
 * @param {Object} props - Props for positioning and scaling the model.
 * @returns {JSX.Element} - React component representing the 3D candlestick model.
 */
export default function Model(props) {
  // Load the GLTF model and extract nodes and materials
  const { nodes, materials } = useGLTF(CandleStickGlb);

  // Render the 3D candlestick model and its components
  return (
    <group
      {...props}
      dispose={null} // Prevent auto-disposal of this group
      scale={[0.03, 0.03, 0.03]} // Scale the model for appropriate size in the scene
      position={[0, -0.2, -0.7]} // Position the model in 3D space
    >
      {/* Render different parts of the candlestick with specific materials */}
      <mesh
        geometry={nodes.Object01.geometry}
        material={materials.Plastic_white}
      >
        {/* Override default material color */}
        <meshStandardMaterial color="#528881" attach="material" />
      </mesh>
      <mesh geometry={nodes.Object03.geometry} material={materials.Fabric} />
      <mesh geometry={nodes.Object02.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Object02_1.geometry} material={materials.Wax} />
    </group>
  );
}

// Preload the GLTF model to ensure it's ready for rendering when used in the application
useGLTF.preload(CandleStickGlb);
