/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\CeramicPot.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import ceramicPotGlb from "../modals/CeramicPot.glb";

export default function Model(props) {
  const { nodes, materials } = useGLTF(ceramicPotGlb);
  console.log({ nodes });
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Ceramic_pot.geometry}
        material={materials.Ceramic_pot}
        scale={[3, 3, 3]}
        position={[0.2, -0.1, -0.8]}
      />
    </group>
  );
}

useGLTF.preload(ceramicPotGlb);
