/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\NapoleanGlb.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import NapoleanGlb from "../modals/NapoleanGlb.glb";

export default function Model(props) {
  const { nodes, materials } = useGLTF(NapoleanGlb);
  return (
    <group
      {...props}
      dispose={null}
      scale={[0.002, 0.002, 0.002]}
      rotation={[-Math.PI / 2, 0, 0]}
      position={[0, 0.4, -0.5]}
    >
      <mesh geometry={nodes.napoleon.geometry} material={materials.Marble} />
    </group>
  );
}

useGLTF.preload(NapoleanGlb);
