/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\NesCafeGlb.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import NesCafeGlb from "../modals/NesCafeGlb.glb";

export default function Model(props) {
  const { nodes, materials } = useGLTF(NesCafeGlb);
  return (
    <group
      {...props}
      dispose={null}
      scale={[10, 10, 10]}
      position={[0, -0.2, -0.8]}
    >
      <mesh geometry={nodes.mug_Circle.geometry} material={materials.Mat_1}>
        <meshStandardMaterial color="#645188" attach="material" />
      </mesh>
    </group>
  );
}

useGLTF.preload(NesCafeGlb);
