/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\OpenCabinet.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import OpenCabinetGlb from "../modals/OpenCabinet.glb";

function OpenCabinet(props) {
  const { nodes, materials } = useGLTF(OpenCabinetGlb);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.left_plank002.geometry}
        material={materials.Material}
        position={[0.002, 0.003, -0.006]}
      />
      <mesh
        geometry={nodes.right_plank002.geometry}
        material={materials["Material.003"]}
        position={[0.004, 0.148, -1.484]}
      />
      <mesh
        geometry={nodes.top_plank002.geometry}
        material={materials["Material.002"]}
        position={[-0.001, 1.023, -0.744]}
      />
      <mesh
        geometry={nodes.bottom_plank002.geometry}
        material={materials["Material.004"]}
        position={[-0.008, -0.267, -0.742]}
      />
      <mesh
        geometry={nodes.back_plank002.geometry}
        material={materials["Material.005"]}
        position={[-0.6, 0.315, -0.746]}
        scale={[1, 0.958, 0.946]}
      />
    </group>
  );
}

export default OpenCabinet;

useGLTF.preload(OpenCabinetGlb);
