/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\src\modals\Person.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import PersonGlb from "../modals/Person.glb";

function Person(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(PersonGlb);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group name="Person" rotation={[Math.PI / 2, 0, 0]}>
          <group name="rp_sophia_animated_003_idling_CTRL">
            <primitive object={nodes.rp_sophia_animated_003_idling_root} />
          </group>
          <group name="rp_sophia_animated_003_idling_geoGRP">
            <skinnedMesh
              name="rp_sophia_animated_003_idling_geo"
              geometry={nodes.rp_sophia_animated_003_idling_geo.geometry}
              material={materials.rp_sophia_animated_003_mat}
              skeleton={nodes.rp_sophia_animated_003_idling_geo.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(PersonGlb);

export default Person;
